### ISSUE TITLE
403: Unauthorised access type

### ISSUE THREAD

**Issue by jayrobwilliams** [chris-dworschak/acled.api#2]
Any query I try to make (including the example queries in the documentation) I receive the following error: `GET request wasn't successful. The API returned status 403: Unauthorised access type.` I know my email and access key are correct because if I change either of them I get: `GET request wasn't successful. The API returned status 403: Access key and email address are not authorized.` Is there something I'm doing wrong, or is this something I should contact ACLED about?

**Comment by jayrobwilliams** [comment]
Turns out I had to get my API key access upgraded by ACLED in order to use the API key in GET and POST calls and not just on the website.

**Comment by chris-dworschak** [comment]
Sorry for the late reply; glad this got sorted out!
