### ISSUE TITLE
More filter arguments

### ISSUE THREAD

**Issue by jayrobwilliams** [chris-dworschak/acled.api#3]
Do you have any interest in adding more filter arguments to the function? I'm specifically thinking of an argument to filter on interaction type, as well as the type codes for actor 1 and actor 2. That seems like a pretty common way people are subsetting the ACLED data, and it would be useful for people to not have to dig into the API documentation to figure out how to write an `other.query` for it. If you're interested, I can write one up and submit a pull request for it. Happy to add any other filters you think would be handy as well.

**Comment by chris-dworschak** [comment]
That's a great suggestion. Currently this is possible through the other.query argument, but I agree that this could be specifically integrated. This GitHub repo is no longer active (everything was moved to GitLab), but I'll have a go at it over the next few days. Cheers!

**Comment by jayrobwilliams** [comment]
Yeah I noticed that note after I opened this issue. I can also take a crack at it and submit a merge request over on GitLab if you want; I've been using filters pretty aggressively for a project this past week so I could throw something together quickly.

**Comment by chris-dworschak** [comment]
Sure please feel free to! Or you can just send the API query strings over as they are and I integrate them as arguments, that'd already be helpful.

**Comment by jayrobwilliams** [comment]
Submitted a merge request over on GitLab!
