### ISSUE TITLE
Add GitHub URL to DESCRIPTION

### ISSUE THREAD

**Issue by andybega** [chris-dworschak/acled.api#4]
Hi, just a super minor thing, but if you add the GitHub repo url to the DESCRIPTION file it will be easier to end up here from the package CRAN page, which I just tried to do. 

```
URL: https://github.com/chris-dworschak/acled.api
```

And maybe also for bug reports:

```
BugReports: https://github.com/chris-dworschak/acled.api/issues
```

**Comment by chris-dworschak** [comment]
Thanks a lot Andreas! This is especially relevant given that it's actually not GitHub, but GitLab, where it's being maintained. On its way to CRAN with the fix.

**Comment by andybega** [comment]
Oh, ok, yeah. Why do you have a mirror here at all?

**Comment by chris-dworschak** [comment]
Mere function of GitHub's popularity, making it easier for most people to follow updates. Thanks again Andreas
